name: build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - {cc: 'gcc', cxx: 'g++'}
          - {cc: 'clang', cxx: 'clang++'}
        build_type:
          - Debug
          - MinSizeRel
    name: build with ${{ matrix.compiler.cc }} type ${{ matrix.build_type }}
    steps:
      - uses: actions/checkout@v4
      - run: |
          bash -c 'echo "set man-db/auto-update false" | sudo debconf-communicate' && \
          sudo dpkg-reconfigure man-db && \
          sudo apt-get update && \
          sudo apt-get install -y nasm
      - run: tools/install-sdl3.sh
      - run: ${{ matrix.compiler.cc }} --version
      - run: |
          cmake -B ${{github.workspace}}/build-native \
              -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
              -DCMAKE_C_COMPILER=${{ matrix.compiler.cc }} \
              -DCMAKE_CXX_COMPILER=${{ matrix.compiler.cxx }}
      - run: cmake --build ${{github.workspace}}/build-native -j$(nproc)
      - run: ctest --test-dir build-native/core --verbose -j$(nproc)
      - run: core/tests/cpu/cpu_demo_test.sh
      - working-directory: ${{github.workspace}}/build-native/core
        run: ls -lh *.a
      - run: emcmake cmake -B ${{github.workspace}}/build-emscripten
      - run: cmake --build ${{github.workspace}}/build-emscripten -j$(nproc)
      - working-directory: ${{github.workspace}}/build-emscripten/sdl
        run: ls -lh yax86_sdl.*
      - run: git diff --exit-code
